export const inputSchema = {
  name: "",
  phone: "",
  address: "",
  tgl: "",
  judul: "",
  penulis: "",
  catberita: "",
  catdaerah: "",
  content: "",
  thumbnail: "",
  tag: [{ tag: "" }],
  desc: "",
  image: "",
};

export const errorSchema = {
  name: "",
  phone: "",
  address: "",
  tgl: "",
  judul: "",
  penulis: "",
  catberita: "",
  catdaerah: "",
  content: "",
  thumbnail: "",
  tag: [{ tag: "" }],
  desc: "",
  image: "",
};
