export async function getStaticMenus() {
  const menus = [
    { path: "/internasional", text: "Internasional" },
    { path: "/nasional", text: "Nasional" },
    { path: "/kabar-daerah", text: "Kabar Daerah" },
    { path: "/pifabiz", text: "PifaBiz" },
    { path: "/politik", text: "Politik" },
    { path: "/bola-dan-sports", text: "Bola dan Sports" },
    { path: "/bisnis", text: "Bisnis" },
    { path: "/teknologi", text: "Teknologi" },
    { path: "/food-dan-travel", text: "Food dan Travel" },
    { path: "/lifestyle", text: "Lifestyle" },
    { path: "/iklan-disini", text: "Iklan Disini" },
  ];

  return menus;
}

export async function getContactInfo() {
  const contacts = [
    {
      id: "1",
      label: "(+62) 811 5737 688",
      value: "(+62) 811 5737 688",
      icon: "/svg/phone.svg",
    },
    {
      id: "2",
      label: "nettacodeindonesia@gmail.com",
      value: "nettacodeindonesia@gmail.com",
      icon: "/svg/email.svg",
    },
  ];

  return contacts;
}

export async function getSocialInfo() {
  const socials = [
    {
      id: "1",
      label: "PIFA on Instagram",
      value: "https://instagram.com/pifa.co.id",
      icon: "/svg/instagram.svg",
    },
    {
      id: "2",
      label: "PIFA on Facebook",
      value: "https://www.facebook.com/Pifa-175960317881224",
      icon: "/svg/facebook.svg",
    },
    {
      id: "3",
      label: "PIFA on YouTube",
      value: "https://www.youtube.com/channel/UChd3pp48NwGI0afTn3dgm7g",
      icon: "/svg/youtube.svg",
    },
  ];

  return socials;
}

export async function getStaticPages() {
  const pages = [
    {
      id: "1",
      title: "Navigasi",
      items: [
        { itemid: "1", name: "Syarat & Ketentuan", path: "/syarat-ketentuan" },
        { itemid: "2", name: "Tentang PIFA", path: "/tentang-pifa" },
        { itemid: "3", name: "Kebijakan Privasi", path: "/kebijakan-privasi" },
        { itemid: "4", name: "Bantuan (FAQ)", path: "/faq" },
      ],
    },
    {
      id: "2",
      title: "Panduan",
      items: [
        {
          itemid: "1",
          name: "Kode Etik Jurnalistik",
          path: "/kode-etik-jurnalistik",
        },
        { itemid: "2", name: "Beriklan", path: "/pasang-iklan" },
        {
          itemid: "3",
          name: "Pedoman Media Siber",
          path: "/pedoman-media-siber",
        },
      ],
    },
  ];

  return pages;
}

const posts = [
  {
    post_id: "1",
    post_title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
    post_short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    post_thumbnail: "/img/img-01.jpg",
    post_category: "Kabar Daerah",
    post_content: "",
    post_location: "Indonesia",
    post_tags: [
      { tag_label: "Pontianak", tag_value: "pontianak" },
      { tag_label: "Pilpres 2024", tag_value: "pilpres-2024" },
      { tag_label: "Indonesia U23", tag_value: "indonesia-u23" },
    ],
    post_view: "88",
    datetimecreate: "20 Jan 2024",
    datetimeupdate: "20 Jan 2024",
  },
];

const tags = [
  {
    tag_id: "1",
    tag_label: "Pilpres 2024",
    tag_value: "pilpres-2024",
  },
];

export async function getFeaturedPosts() {
  const posts = [
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Kabar Daerah",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "PifaBiz",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Bisnis",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Kabar Daerah",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Kabar Daerah",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Teknologi",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Kabar Daerah",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "PifaBiz",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "PifaBiz",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "PifaBiz",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Teknologi",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Teknologi",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Teknologi",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Bisnis",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Bisnis",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Bisnis",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Lifestyle",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Lifestyle",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Lifestyle",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Lifestyle",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Bola dan Sports",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Bola dan Sports",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Bola dan Sports",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Bola dan Sports",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Politik",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Politik",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Politik",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Politik",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Nasional",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Nasional",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Nasional",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Nasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Internasional",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Internasional",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Internasional",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Internasional",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "1",
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui.",
      short: "Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
      tag: "Food dan Travel",
      image: "/img/img-01.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "2",
      title: "Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio.",
      short: "Phasellus ac tellus non neque pellentesque laoreet. Aenean sit amet",
      tag: "Food dan Travel",
      image: "/img/img-02.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "3",
      title: "elit sit amet sem ornare blandit. Quisque in augue id ligula auctor",
      short: "mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie",
      tag: "Food dan Travel",
      image: "/img/img-03.jpg",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "4",
      title: "aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      short: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium ",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "5",
      title: "egestas. Pellentesque a luctus mi, sit amet ornare erat. Etiam commodo",
      short: "pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "6",
      title: "Fusce nunc quam, posuere in ornare nec, eleifend in lectus. Donec euismod orci",
      short: "neque. In maximus dictum pellentesque. Fusce vulputate pulvinar enim vel ",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "7",
      title: "volutpat. Phasellus eget mauris nec nibh consequat congue nec quis dolor.",
      short: "Nulla ante felis, rutrum id dignissim in, aliquam a tortor. Cras elementum",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "8",
      title: "neque sed orci egestas viverra. In dictum at lacus sed faucibus.",
      short: "Suspendisse ligula lectus, tempor nec semper et, blandit id dolor. Donec vel",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "9",
      title: "velit sem. Quisque in condimentum risus. Sed at consequat nisl. Aliquam ",
      short: "sit amet turpis nec mauris tempus maximus. Morbi turpis ipsum, commodo et",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "10",
      title: "dolor vel, molestie malesuada tortor. Morbi libero purus, facilisis et diam",
      short: "vel, pellentesque facilisis massa. Aliquam erat volutpat. Maecenas ",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "11",
      title: "placerat lorem eget purus semper maximus. Quisque placerat faucibus",
      short: "dapibus. In ac justo sed ipsum elementum dictum. Etiam mattis, massa",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "12",
      title: "sit amet molestie porta, ex sapien sollicitudin ex, pulvinar vestibulum",
      short: "diam dui et lectus. Morbi id ornare nibh. Nunc viverra quam vel nisi",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "13",
      title: "ultricies, id mollis massa mollis. Suspendisse pellentesque, magna eu",
      short: "consequat ultricies, leo nulla maximus diam, ut sodales justo dolor ut nunc.",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "14",
      title: "Proin tempus condimentum blandit. In dictum rutrum turpis sed ultrices.",
      short: "Pellentesque rutrum tortor sed felis imperdiet imperdiet. Nulla id fringilla",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
    {
      id: "15",
      title: "odio, tempus tincidunt massa. Nullam hendrerit cursus dui, vel egestas ante",
      short: "fermentum at. Sed sit amet porttitor nisi, ut porta massa. Nunc a magna",
      tag: "Food dan Travel",
      image: "",
      location: "Indonesia",
      date: "20 Jan 2024",
    },
  ];

  return posts;
}

export async function getTrendingTags() {
  const tags = [
    { value: "pilpres-2024", label: "Pilpres 2024" },
    { value: "kalbar", label: "Kalbar" },
    { value: "indonesia-u23", label: "Indonesia U23" },
    { value: "gempa-bumi", label: "Gempa Bumi" },
  ];

  return tags;
}

export async function getLocalCategories() {
  const cats = [
    { id: "1", name: "Pontianak", image: "/img/img-01.jpg" },
    { id: "2", name: "Kubu Raya", image: "/img/img-02.jpg" },
    { id: "3", name: "Mempawah", image: "/img/img-03.jpg" },
    { id: "4", name: "Singkawang", image: "" },
    { id: "5", name: "Bengkayang", image: "" },
    { id: "6", name: "Sambas", image: "" },
    { id: "7", name: "Landak", image: "" },
    { id: "8", name: "Sanggau", image: "" },
    { id: "9", name: "Sekadau", image: "" },
    { id: "10", name: "Sintang", image: "" },
    { id: "11", name: "Melawi", image: "" },
    { id: "12", name: "Kapuas Hulu", image: "" },
    { id: "13", name: "Ketapang", image: "" },
    { id: "14", name: "Kayong Utara", image: "" },
  ];

  return cats;
}

export async function getInfographicPosts() {
  const posts = [
    {
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod.",
      image: "/img/graphic/art-1.jpg",
      count: "4",
      status: "BARU",
    },
    {
      title: "In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia.",
      image: "/img/graphic/art-2.jpg",
      count: "7",
      status: "UPDATE",
    },
    {
      title: "Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.",
      image: "/img/graphic/art-3.jpg",
      count: "1",
      status: "BARU",
    },
    { title: "Aenean sit amet elit sit amet sem ornare blandit.", image: "/img/graphic/art-4.jpg", count: "12", status: "" },
    {
      title: "Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl.",
      image: "/img/graphic/art-5.jpg",
      count: "2",
      status: "UPDATE",
    },
    {
      title: "Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi.",
      image: "/img/graphic/art-6.jpg",
      count: "8",
      status: "",
    },
    {
      title: "Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas.",
      image: "/img/graphic/art-7.jpg",
      count: "23",
      status: "",
    },
  ];

  return posts;
}

export async function getAdDatas() {
  const ads = [
    { label: "", image: "/img/ad/1696303634.webp" },
    { label: "", image: "/img/ad/1654149291.webp" },
    { label: "", image: "/img/ad/1654149341.webp" },
    { label: "", image: "/img/ad/1654149110.webp" },
    { label: "", image: "/img/ad/1696303634.webp" },
    { label: "", image: "/img/ad/1654149291.webp" },
    { label: "", image: "/img/ad/1654149341.webp" },
    { label: "", image: "/img/ad/1654149110.webp" },
  ];

  return ads;
}
