name: PIFA v0.1.0

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  web-deploy:
    name: Deploy on Main
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: 1. Get latest code
        uses: actions/checkout@v2

      - name: 2. Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. Export environment variables
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_MAIN=${{ secrets.REACT_APP_DOMAIN_MAIN }}" >> $GITHUB_ENV
          echo "REACT_APP_MARKERS=${{ secrets.REACT_APP_MARKERS }}" >> $GITHUB_ENV
          echo "REACT_APP_GTAG_MAIN=${{ secrets.REACT_APP_GTAG_MAIN }}" >> $GITHUB_ENV

      - name: 4. Installing required packages
        run: npm install

      - name: 5. Generate latest sitemap
        run: node update-slugs.js
        env:
          REACT_APP_DOMAIN_MAIN: ${{ secrets.REACT_APP_DOMAIN_MAIN }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: 6. Builds the app for production
        run: CI= npm run stagen

      - name: 7. List output files
        run: find build/ -print

      - name: 8. Sync files (excluding berita folder)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME_MAIN }}
          password: ${{ secrets.FTP_PASSWORD_MAIN }}
          local-dir: build/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/berita/**
            **/img/**
            **/png/**
            **/svg/**

      - name: 9. Sync "berita" folder
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME_MAIN }}
          password: ${{ secrets.FTP_PASSWORD_MAIN }}
          local-dir: build/berita/
          server-dir: berita/

      - name: 10. Remove FTP sync state file
        run: |
          echo "open ${{ secrets.FTP_HOST }}" >> ftp_commands_async.txt
          echo "user ${{ secrets.FTP_USERNAME_MAIN }} ${{ secrets.FTP_PASSWORD_MAIN }}" >> ftp_commands_async.txt

          echo "cd /berita" >> ftp_commands_async.txt
          echo "delete .ftp-deploy-sync-state.json" >> ftp_commands_async.txt
          echo "bye" >> ftp_commands_async.txt

          ftp -inv < ftp_commands_async.txt
