name: PIFA AREA v0.1.0 (push || cron)

on:
  push:
    branches:
      - area
    workflow_run:
      if: github.actor != 'github-actions[bot]'

jobs:
  fetch-subdomains:
    name: 1. Fetch Subdomain Data
    runs-on: ubuntu-latest
    outputs:
      subdomains: ${{ steps.prepare_subdomains.outputs.subdomains_matrix }}

    steps:
      - name: 1.1. Get Subdomains from API
        id: fetch_data
        run: |
          curl -s https://api.pifa.co.id/main/categoryarea -o subdomains.json

      - name: 1.2. Save Subdomains Matrix
        id: prepare_subdomains
        run: |
          SUBDOMAIN_MATRIX=$(jq -c '.data | map({id: .id, name: .nama_kategori_daerah, sub: .subdomain, call: (.subdomain | ascii_upcase)})' subdomains.json)
          echo "subdomains_matrix=$SUBDOMAIN_MATRIX" >> $GITHUB_ENV
          echo "::set-output name=subdomains_matrix::$SUBDOMAIN_MATRIX"

  deploy:
    name: 2. Deploy to Subdomains
    needs: fetch-subdomains
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.1]
        subdomain: ${{ fromJson(needs.fetch-subdomains.outputs.subdomains) }}

    steps:
      - name: 2.1. Get latest code
        uses: actions/checkout@v2

      - name: 2.2. Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 2.3. Export environment variables for ${{ matrix.subdomain.name }}
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: |
          echo "REACT_APP_DOMAIN_AREA=${{ matrix.subdomain.sub }}" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_AREA_NAME=${{ matrix.subdomain.name }}" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_AREA_ID=${{ matrix.subdomain.id }}" >> $GITHUB_ENV

          echo "FTP_USERNAME=${{ secrets[format('FTP_USERNAME_{0}', matrix.subdomain.call)] }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets[format('FTP_PASSWORD_{0}', matrix.subdomain.call)] }}" >> $GITHUB_ENV
          echo "Username: ${{ secrets[format('FTP_USERNAME_{0}', matrix.subdomain.call)] }}, Password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.subdomain.call)] }}"

          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_MARKERS=${{ secrets.REACT_APP_MARKERS }}" >> $GITHUB_ENV
          echo "REACT_APP_GTAG_MAIN=${{ secrets.REACT_APP_GTAG_MAIN }}" >> $GITHUB_ENV
          echo "REACT_APP_CA_PUB_MAIN=${{ secrets.REACT_APP_CA_PUB_MAIN }}" >> $GITHUB_ENV

      - name: 2.4. Installing required packages
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: npm install

      - name: 2.5. Generate latest sitemap
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: node update-slugs.js
        env:
          REACT_APP_DOMAIN_AREA: ${{ matrix.subdomain.sub }}
          REACT_APP_DOMAIN_AREA_ID: ${{ matrix.subdomain.id }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: 2.7. Builds the app for production
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: CI= npm run spagen

      - name: 2.8. List output files
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: find build/ -print

      - name: 2.9. Rename sitemap file for deployment
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: |
          if [ -f build/${{ matrix.subdomain.sub }}_sitemap.xml ]; then
            mv build/${{ matrix.subdomain.sub }}_sitemap.xml build/sitemap.xml
          else
            echo "No sitemap file found for ${{ matrix.subdomain.sub }}."
          fi

      - name: 2.10. Sync files (excluding berita folder)
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets[format('FTP_USERNAME_{0}', matrix.subdomain.call)] }}
          password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.subdomain.call)] }}
          local-dir: build/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/berita/**

      - name: 2.11. Commit and push updated ${{ matrix.subdomain.sub }}_sitemap.xml
        if: ${{ matrix.subdomain.call != 'INTERNASIONAL' && matrix.subdomain.call != 'KALBAR' && matrix.subdomain.call != 'INDONESIA' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git stash push --include-untracked -m "Temp stash before pull"

          git fetch origin area
          git checkout area
          git pull origin area --rebase

          git stash pop || echo "Nothing to pop from stash"

          if git diff --quiet public/${{ matrix.subdomain.sub }}_sitemap.xml; then
            echo "No changes detected in ${{ matrix.subdomain.sub }}_sitemap.xml. Skipping commit."
          else
            git add public/${{ matrix.subdomain.sub }}_sitemap.xml
            git commit -m "Update ${{ matrix.subdomain.sub }}_sitemap.xml from GitHub Actions"
            git push origin area
          fi
